/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberosgrupo5.vistas;

import bomberosgrupo5.accesoADatos.CuartelData;
import bomberosgrupo5.entidades.Cuartel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaco
 */
public class ModificarCuartel extends javax.swing.JInternalFrame {

    private CuartelData cua = new CuartelData();

    /**
     * Creates new form ModificarCuartel
     */
    public ModificarCuartel() {
        initComponents();
        llenarComboCuartel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCCuartel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jTLatitud = new javax.swing.JTextField();
        jTlongitud = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jTCorreo = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Seleccione el Cuartel");

        jCCuartel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCCuartelMouseClicked(evt);
            }
        });
        jCCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCuartelActionPerformed(evt);
            }
        });

        jLabel2.setText("Direccion:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Latitud:");

        jLabel5.setText("Longitud:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Correo:");

        jBGuardar.setText("Guardar Cambios");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBGuardar)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(jTTelefono)
                                    .addComponent(jTLatitud)
                                    .addComponent(jTDireccion)
                                    .addComponent(jTlongitud, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTNombre))))))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTlongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir)
                    .addComponent(jButton1))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCCuartelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCCuartelMouseClicked

//        String cuartelSeleccionado = (String) jCCuartel.getSelectedItem();
//
//        if (cuartelSeleccionado != null) {
//
//            int idCuartel = Integer.parseInt(cuartelSeleccionado.split("\\. ")[0]);
//            Cuartel cuartel = cua.buscarCuartelPorId(idCuartel);
//
//            if (cuartel != null) {
//                jTNombre.setText(cuartel.getNombreCuartel());
//                jTDireccion.setText(cuartel.getDireccion());
////                int coordX = Integer.parseInt(title)
//                jTlongitud.setText(Integer.toString(cuartel.getCoordX()));
//                jTLatitud.setText(Integer.toString(cuartel.getCoordY()));
//                jTTelefono.setText(cuartel.getTelefono());
//                jTCorreo.setText(cuartel.getCorreo());
//
//            }

    }//GEN-LAST:event_jCCuartelMouseClicked

    private void jCCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCuartelActionPerformed
        String cuartelSeleccionado = (String) jCCuartel.getSelectedItem();

        if (cuartelSeleccionado != null) {

            int idCuartel = Integer.parseInt(cuartelSeleccionado.split("\\. ")[0]);
            Cuartel cuartel = cua.buscarCuartelPorId(idCuartel);

            if (cuartel != null) {
                jTNombre.setText(cuartel.getNombreCuartel());
                jTDireccion.setText(cuartel.getDireccion());
//                int coordX = Integer.parseInt(title)
                jTlongitud.setText(Integer.toString(cuartel.getCoordX()));
                jTLatitud.setText(Integer.toString(cuartel.getCoordY()));
                jTTelefono.setText(cuartel.getTelefono());
                jTCorreo.setText(cuartel.getCorreo());

            }
        }
    }//GEN-LAST:event_jCCuartelActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        String cuartelSeleccionado = (String) jCCuartel.getSelectedItem();

        if (cuartelSeleccionado != null) {

            int idCuartel = Integer.parseInt(cuartelSeleccionado.split("\\. ")[0]);

            String nuevoNombre = jTNombre.getText();
            String nuevaDireccion = jTDireccion.getText();
            int nuevaCoordX = Integer.parseInt(jTlongitud.getText());
            int nuevaCoordY = Integer.parseInt(jTLatitud.getText());
            String nuevoTelefono = jTTelefono.getText();
            String nuevoCorreo = jTCorreo.getText();
            
            Cuartel cuartelActualizado = new Cuartel (idCuartel, nuevoNombre, nuevaDireccion, nuevaCoordX, nuevaCoordY, nuevoTelefono, nuevoCorreo, true);
            cua.modificarCuartel(cuartelActualizado);


    }//GEN-LAST:event_jBGuardarActionPerformed
    }
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTNombre.setText("");
                jTDireccion.setText("");
                jTlongitud.setText("");
                jTLatitud.setText("");
                jTTelefono.setText("");
                jTCorreo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    

    

    private void llenarComboCuartel() {
        List<String> nombresCuartel = cua.mostrarOpcionesYObtenerSeleccion();

        if (!nombresCuartel.isEmpty()) {

            jCCuartel.removeAllItems();
            for (String nombre : nombresCuartel) {
                jCCuartel.addItem(nombre);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron cuarteles.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCCuartel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTLatitud;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTextField jTlongitud;
    // End of variables declaration//GEN-END:variables
}
