/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberosgrupo5.vistas;

import bomberosgrupo5.accesoADatos.BrigadaData;
import bomberosgrupo5.entidades.Brigada;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaco
 */
public class ModificarBrigada extends javax.swing.JInternalFrame {

    private BrigadaData briga = new BrigadaData();

    /**
     * Creates new form ModificarCuartel
     */
    public ModificarBrigada() {
        initComponents();
        llenarComboBrigada();
        llenarComboEspecialidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCBrigada = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jCEspecialidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Seleccione la brigada");

        jCBrigada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBrigadaMouseClicked(evt);
            }
        });
        jCBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBrigadaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jBGuardar.setText("Guardar Cambios");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jCEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCEspecialidadMouseClicked(evt);
            }
        });
        jCEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEspecialidadActionPerformed(evt);
            }
        });

        jLabel8.setText("Seleccione especialidad");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBrigada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBGuardar)
                                .addGap(48, 48, 48)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15)
                                .addComponent(jTNombre)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir)
                    .addComponent(jButton1))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBrigadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBrigadaMouseClicked

//        String cuartelSeleccionado = (String) jCCuartel.getSelectedItem();
//
//        if (cuartelSeleccionado != null) {
//
//            int idCuartel = Integer.parseInt(cuartelSeleccionado.split("\\. ")[0]);
//            Cuartel cuartel = cua.buscarCuartelPorId(idCuartel);
//
//            if (cuartel != null) {
//                jTNombre.setText(cuartel.getNombreCuartel());
//                jTDireccion.setText(cuartel.getDireccion());
////                int coordX = Integer.parseInt(title)
//                jTlongitud.setText(Integer.toString(cuartel.getCoordX()));
//                jTLatitud.setText(Integer.toString(cuartel.getCoordY()));
//                jTTelefono.setText(cuartel.getTelefono());
//                jTCorreo.setText(cuartel.getCorreo());
//
//            }

    }//GEN-LAST:event_jCBrigadaMouseClicked

    private void jCBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBrigadaActionPerformed
        String brigadaSelec = (String) jCBrigada.getSelectedItem();
        
        if (brigadaSelec != null) {

            int idCuartel = Integer.parseInt(brigadaSelec.split("\\. ")[0]);
            Brigada brigada = briga.buscarBrigadaPorId(idCuartel);

            if (brigada != null) {
                jTNombre.setText(brigada.getNombreBrig());
//                jTDireccion.setText(cuartel.getDireccion());
////                int coordX = Integer.parseInt(title)
//                jTlongitud.setText(Integer.toString(cuartel.getCoordX()));
//                jTLatitud.setText(Integer.toString(cuartel.getCoordY()));
//                jTTelefono.setText(cuartel.getTelefono());
//                jTCorreo.setText(cuartel.getCorreo());

            }
        }
        
        
    }//GEN-LAST:event_jCBrigadaActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        String brigadaSelec = (String) jCBrigada.getSelectedItem();

        if (brigadaSelec != null) {

            int idBrigada = Integer.parseInt(brigadaSelec.split("\\. ")[0]);

            String nuevoNombre = jTNombre.getText();
            String nuevaEspecialidad = (String) jCEspecialidad.getSelectedItem();
            
            //Brigada BrigadaActualizada = new Brigada (nuevoNombre, nuevaEspecialidad);
            briga.modificarBrigada(idBrigada, nuevoNombre, nuevaEspecialidad);
            //JOptionPane.showMessageDialog(null, "Brigada Modificada");


    }//GEN-LAST:event_jBGuardarActionPerformed
    }
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jCEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCEspecialidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEspecialidadMouseClicked

    private void jCEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEspecialidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTNombre.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    

    private void llenarComboEspecialidades() {
        String[] especialidades = briga.Especialidades();
        jCEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(especialidades));
    }

    
        private void llenarComboBrigada() {
        List<String> nombresBrigada = briga.mostrarOpciones();

        if (!nombresBrigada.isEmpty()) {
            // Limpiamos el JComboBox antes de agregar los nuevos elementos
            jCBrigada.removeAllItems();
            for (String nombre : nombresBrigada) {
                jCBrigada.addItem(nombre);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron brigadas");
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBrigada;
    private javax.swing.JComboBox<String> jCEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
